---

- name: Add model device by serial number.
  fmgr_dvm_cmd_add_device:
    dvm_cmd_add_device:
      adom: "{{ customer_facts['adom_name'] }}"
      device:
        adm_usr: "admin"
        adm_pass: ""
        desc: "Added by ansible"
        device action: "add_model"
        meta fields:
          Billing Code: "{{ line_facts['billing_id'] | default(omit)}}"
          Company/Organization: "{{ customer_facts['name'] }}"
          Contact Email: "{{ customer_facts['tech_contact']['email'] | default(omit)}}"
          Contact Phone Number: "{{ customer_facts['tech_contact']['phone'] | default(omit)}}"
        mgmt_mode: "fmg"
        mr: 2
        name: "{{ serial }}"
        os_type: "fos"
        os_ver: "6.0"
        sn: "{{ serial }}"

- name: Set device flags for ZTP.
  fmgr_dvmdb_device:
    adom: "{{ customer_facts['adom_name'] }}"
    device: "{{ serial }}"
    dvmdb_device:
      flags:
        - "linked_to_model"
        - "is_model"
